name: Deploy Lambda and DynamoDB


env:
  AWS_DDB_MENTOR_TABLE_NAME: atc-mentor
  
on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your region

      - name: Create DynamoDB Table
        run: |
          aws dynamodb create-table \
            --table-name ${{env.AWS_DDB_MENTOR_TABLE_NAME}} \
            --attribute-definitions \
              AttributeName=Id,AttributeType=S \
            --key-schema \
              AttributeName=Id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            --region us-east-1  # Change to your region

      - name: "Resolve Project Dependencies Using Npm"
        run: |
          npm install
          npm run build 
          npm run test

      - name: Deploy Lambda Function
        run: |
          aws lambda create-function \
            --function-name home \
            --runtime nodejs20.x \  # Change this to your runtime
            --role arn:aws:iam::022499005689:user/web \  # Update with your IAM role ARN
            --handler index.handler \  # Update based on your handler
            --zip-file fileb://path/to/your/lambda.zip \  # Path to your zipped code

          # Optionally update the Lambda function if it already exists
          aws lambda update-function-code \
            --function-name home \
            --zip-file fileb://path/to/your/lambda.zip
