name: Deploy Lambda and DynamoDB

env:
  AWS_DDB_MENTOR_TABLE_NAME: atc-mentor

on:
  push:
    branches:
      - change_folder_to_aws_lambda # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your region
      - name: Setup sam
        uses: aws-actions/setup-sam@v1
      - name: Sam Build
        run: sam build
      - name: Sam Deploy
        run: sam deploy --no-confirm-changeset
      #   - name: Create DynamoDB Table
      #     run: |
      #       aws dynamodb create-table \
      #         --table-name ${{env.AWS_DDB_MENTOR_TABLE_NAME}} \
      #         --attribute-definitions \
      #           AttributeName=Id,AttributeType=S \
      #         --key-schema \
      #           AttributeName=Id,KeyType=HASH \
      #         --billing-mode PAY_PER_REQUEST \
      #         --region us-east-1


        # aws lambda update-function-code --function-name home --zip-file fileb://path/to/your/lambda.zip
