name: Deploy Lambda and DynamoDB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your region
      - name: Install
        run: npm install --omit=dev
      - name: Compile Types
        run: npx openapi-typescript ./src/schema/openapi.json -o ./src/schema/schema.d.ts
      - name: Build
        run: npm run build
      - name: Prepare Dependencies
        run: cp -r node_modules dist
      - name: 'Deploy Lambda'
        run: npx cdk deploy --require-approval never
